### ISSUE TITLE
changing the json file with array / nsdictionary as datasource

### ISSUE THREAD

**Issue by ekapradityagk** [weijentu/automatic-height-tagcells#12] opened 2018-05-08 12:52 UTC
hi,, can we change the data source from json file, to nsdictionary or array?

me and my friend on a combine project (objc-swift), and him as a swift developer using this library but having a difficulty of getting data to tags label using nsdictionary or array, and he change it to sqllite, but the issue become bigger.. currently i already convert the code in swift to get the selected data to nsarray, but i still struggling for setup the setTags file.

`                if self.fundArr.count != 0 {
                    print(self.fundArr.count)
                    var arrSourceFound = self.fundArr
                    for element in arrSourceFound {
                        print(element)
                    }
//                    for index in 0...self.fundArr.count - 1  {
//                        let sourcefund:SqlLite_SourceFund = self.fundArr.object(at: index) as! SqlLite_SourceFund
////                        print("data source fund " + sourcefund)
////                        for (myKey,myValue) in sourcefund {
////                            print("\(myKey) \t \(myValue)")
////                        }
//                        arrSourceFound.append(sourcefund)
//                    }
                    cell.label.setTags(arrSourceFound as! [AHTag])`

this is what im struggling for, to settags my array as ahtag, its quite hard for me since i am an objective c developer, and this code need to be done using swift (his partt)
     the one in commented is what my partner doing,, he changed it to sqllite, but its become a bigger issue, thats why i want to convert it to nsdictionary / nsarray as a datasource

hope anyone here can help me to solve this issue..
regards,
Eka

**Comment by weijentu** [comment] 2018-05-09 01:55
@ekapradityagk json file is just a data source for demo purpose. Of course, you can have `NSArray <NSDictionary *>* array` with `AHTag`. The only thing you have to do is to set a for-loop to create `AHTag` objects and set properties according to key and value in your `NSDictionary` object.

**Comment by ekapradityagk** [comment] 2018-05-09 05:03
@weijentu hi, thank you for the quick response.

i only touch swift code several years ago while its still swift 2, 
can you help me more on this? which part i need to check on the code and which part i need to change to?

i even didnt know whats as! in this line is mean
cell.label.setTags(arrSourceFound as! [AHTag])

what i know is settags will need a set of array to processed in the section, but when i parse my array, using this 
cell.label.setTags(self.fundArr) <- this is array with the dictionary object of choice 
or with this
cell.label.setTags(arrSourceFound as! [AHTag]) 
i cant compile it. thats what im struggling at.

can i do this without changing any of your library? 
notes:(my friend changed AHTagsLabel.swift into sqllite model, but i can just switch it back with yours if you say i didnt need to change anything and just parse the array)

**Comment by weijentu** [comment] 2018-05-09 05:18
The part you are asking has nothing to do with AHTag. Also the code you paste didn't tell me any detail. The issue you are facing is related to basic ideas of how to process dictionary and array. I would recommend you to have more communication with your friends. Sorry that I can't help the code that I can't see and not composed by me.

**Comment by ekapradityagk** [comment] 2018-05-09 05:25
hmm,,

that is the reason i open a ticket in here, he already set his mind that this cant be solved with array or dictionary, so he changed it to sqllite model database, when i try to approach him, he just insisting it cant be done, and its hard for me to solve an issue if one of the people already decide to give up >.<

can you help me as if i change your code? i will redownload your code, and help me to point out in yours which part i need to change to switch to array / dictionary.

**Comment by weijentu** [comment] 2018-05-09 05:40
Basically the original process is from JSON -> array -> dictionary. If you really already have your own array, I can't see any problem that you can't create your own tags. In my opinion, the issue is not about json, array, dictionary or Objective C/Swift. You have to find where is array in your code first, and I'm not the right one to ask.

Sorry I'll close the issue because the title is based on a wrongly understanding and I'm not the right one to have your answer.

**Closed as completed by weijentu** 2018-05-09 05:40 UTC

**Comment by ekapradityagk** [comment] 2018-05-09 05:46
okay,, sorry then, i just hoping if i solve this me and my partner can do a better cooperation in the future. 

thanks for the time.
